insert into Services (Name,url) values ('O365 UK', '');
insert into Services (Name,url) values ('O365+Azure+PowerBI', '');
insert into Services (Name,url) values ('Conflurence+Jira sync with O365', '');
insert into Services (Name,url) values ('Bitbucket', '');
insert into Services (Name,url) values ('On-prem AD', '');
insert into Services (Name,url) values ('Adobe', '');
insert into Services (Name,url) values ('Hubspot', '');
insert into Services (Name,url) values ('OmegaTelecom', '');
insert into Services (Name,url) values ('SumSub', '');
insert into Services (Name,url) values ('Facebook shared', '');
insert into Services (Name,url) values ('AWS', '');
insert into Services (Name,url) values ('Alicloud', '');
insert into Services (Name,url) values ('Kinsta', '');
insert into Services (Name,url) values ('SalesForce', '');
insert into Services (Name,url) values ('Uptimerobot', '');
insert into Services (Name,url) values ('Instagramm shared ', '');
insert into Services (Name,url) values ('DockerHUB', '');
insert into Services (Name,url) values ('TestRail', '');
insert into Services (Name,url) values ('Browserstack', '');
insert into Services (Name,url) values ('Apple App Store Connect', '');
insert into Services (Name,url) values ('Google Search Console', '');
insert into Services (Name,url) values ('Google Play Console', '');
insert into Services (Name,url) values ('GMI Google Play Console', '');
insert into Services (Name,url) values ('Google Firebase Console', '');
insert into Services (Name,url) values ('Google Analytics', '');
insert into Services (Name,url) values ('Google Tag Manager', '');
insert into Services (Name,url) values ('Google Ads / Google Adword', '');
insert into Services (Name,url) values ('Google BigQuery', '');
insert into Services (Name,url) values ('Yandex Metrica', '');
insert into Services (Name,url) values ('Yandex Appmetrica', '');
insert into Services (Name,url) values ('Active cloud', '');
insert into Services (Name,url) values ('Livechat', '');
insert into Services (Name,url) values ('Shutterstock (shared)', '');
insert into Services (Name,url) values ('Shutterstock GMI (shared)', '');
insert into Services (Name,url) values ('Figma', '');
insert into Services (Name,url) values ('CloudFlare', '');
insert into Services (Name,url) values ('1C Finstek', '');
insert into Services (Name,url) values ('Acronis InfoProtect shared IT', '');
insert into Services (Name,url) values ('Advancedcustomfield - shared', '');
insert into Services (Name,url) values ('Ahrefs', '');
insert into Services (Name,url) values ('RDS / VPS', '');
insert into Services (Name,url) values ('SendGrid', '');
insert into Services (Name,url) values ('Netlify  (Shared)', '');
insert into Services (Name,url) values ('Recaptcha', '');
insert into Services (Name,url) values ('Consultant Plus Shared', '');
insert into Services (Name,url) values ('Atlant-Pravo Navigator', '');
insert into Services (Name,url) values ('Azure DevOps', '');
insert into Services (Name,url) values ('AppsFlyer', '');
insert into Services (Name,url) values ('Similarweb', '');
insert into Services (Name,url) values ('SnipeIT', '');
insert into Services (Name,url) values ('Passwordstate', '');
insert into Services (Name,url) values ('App Center', 'https://appcenter.ms');
insert into Services (Name,url) values ('SE Ranking', '');
insert into Services (Name,url) values ('DataGrip', '');
insert into Services (Name,url) values ('CloudTalk', '');